# This file was generated by GoReleaser. DO NOT EDIT.
cask "proton-drive-linux-fs" do
  version "0.22.10"

  on_linux do
    on_arm do
      sha256 "69bcc813d3925af10fd70c3ff76a65ae774d1f1aead9809abbeb80384da1a2ab"
      url "https://github.com/khaosdoctor/proton-drive-linux-fs/releases/download/v#{version}/proton-drive-linux-fs_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b1fa73d6deea0a628cef350bd9b8509312a4087474ecf21046165776c6a4b559"
      url "https://github.com/khaosdoctor/proton-drive-linux-fs/releases/download/v#{version}/proton-drive-linux-fs_#{version}_linux_amd64.tar.gz"
    end
  end

  name "proton-drive-linux-fs"
  desc "FUSE virtual filesystem for Proton Drive on Linux."
  homepage "https://github.com/khaosdoctor/proton-drive-linux-fs"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "libfuse",
    ]

  binary "proton-drive-fs"

  # No zap stanza required
end
