# This file was generated by GoReleaser. DO NOT EDIT.
cask "proton-drive-linux-fs" do
  version "0.22.12"

  on_linux do
    on_arm do
      sha256 "7d690258d78300e691e7d5832b1fc152d6b2e7df680ea8271e522cd4fc0a5d11"
      url "https://github.com/khaosdoctor/proton-drive-linux-fs/releases/download/v#{version}/proton-drive-linux-fs_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b68d2a212a95ba6aec31920e5a3275d72cc92fda355cc845413ae6b79df5984"
      url "https://github.com/khaosdoctor/proton-drive-linux-fs/releases/download/v#{version}/proton-drive-linux-fs_#{version}_linux_amd64.tar.gz"
    end
  end

  name "proton-drive-linux-fs"
  desc "FUSE virtual filesystem for Proton Drive on Linux."
  homepage "https://github.com/khaosdoctor/proton-drive-linux-fs"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "libfuse",
    ]

  binary "proton-drive-fs"

  # No zap stanza required
end
