# This file was generated by GoReleaser. DO NOT EDIT.
cask "proton-drive-linux-fs" do
  version "0.22.11"

  on_linux do
    on_arm do
      sha256 "7bdd4480669c6a88af834d8fe6390833aa0dc0c2699fa267d7053f9d98fb0417"
      url "https://github.com/khaosdoctor/proton-drive-linux-fs/releases/download/v#{version}/proton-drive-linux-fs_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "496bd9281add51c201dc62d615b07e55bfd0954510957e78a426b870c63c9956"
      url "https://github.com/khaosdoctor/proton-drive-linux-fs/releases/download/v#{version}/proton-drive-linux-fs_#{version}_linux_amd64.tar.gz"
    end
  end

  name "proton-drive-linux-fs"
  desc "FUSE virtual filesystem for Proton Drive on Linux."
  homepage "https://github.com/khaosdoctor/proton-drive-linux-fs"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "libfuse",
    ]

  binary "proton-drive-fs"

  # No zap stanza required
end
