# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtonDriveLinuxFs < Formula
  desc "FUSE virtual filesystem for Proton Drive on Linux."
  homepage "https://github.com/khaosdoctor/proton-drive-linux-fs"
  version "0.28.0"
  license "MIT"

  depends_on "libfuse" => :build
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/khaosdoctor/proton-drive-linux-fs/releases/download/v0.28.0/proton-drive-linux-fs_0.28.0_linux_amd64.tar.gz"
    sha256 "d09f9499ec408ab70a47f1cf26d71cf2a8324a099f62056e82d24bb7ccb68a43"
    define_method(:install) do
      bin.install "proton-drive-fs"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/khaosdoctor/proton-drive-linux-fs/releases/download/v0.28.0/proton-drive-linux-fs_0.28.0_linux_arm64.tar.gz"
    sha256 "d26f31b105c9d47b52b55c814717e3b618f0189097389ad0253962356d3dc71e"
    define_method(:install) do
      bin.install "proton-drive-fs"
    end
  end
end
